# Generated by Django 4.2.11 on 2024-04-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="no_picture.jpg", upload_to="recipes"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=75),
        ),
    ]
