# Generated by Django 4.2.11 on 2024-04-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_description_recipe_difficulty_recipe_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Easy", "Easy"),
                    ("Medium", "Medium"),
                    ("Intermediate", "Intermediate"),
                    ("Hard", "Hard"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
