# Generated by Django 4.2.11 on 2024-04-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="difficulty",
        ),
    ]
